# Generated by Django 2.2.6 on 2019-11-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='serial_number',
            field=models.PositiveSmallIntegerField(default=''),
            preserve_default=False,
        ),
    ]
