# Generated by Django 2.2.6 on 2019-11-16 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20191116_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='id',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
