# Generated by Django 2.2.6 on 2019-11-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20191116_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
