# Generated by Django 2.2.6 on 2019-11-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20191116_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
